name: PM-Beacons
main: jasonwynn10\beacon\Beacons
version: 2.0.1
api:
 - 3.0.0
description: "Beacons for PocketMine-MP exactly like Vanilla!"
author: "jasonwynn10"
mcpe-protocol:
 - 431
 - 440
 - 448
